sonar.organization=anas4208-workspace
sonar.projectKey=anas4208-workspace_anas4208-workspace
sonar.projectName=Elmenus Management System
sonar.projectVersion=2.0

sonar.sources=.
sonar.inclusions=Customer.cpp,Customer.h,DeliveryDriver.cpp,DeliveryDriver.h,User.cpp,User.h,main.cpp
sonar.exclusions=**/simple_test.cpp,**/test_driver_only.cpp,**/DuplicateTest.cpp,**/*.o,**/main,**/*.gcda,**/*.gcno

sonar.cfamily.compile-commands=compile_commands.json
sonar.cfamily.cache.enabled=true

sonar.coverageReportPaths=coverage.xml

sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
